### ISSUE TITLE
How to try other mask patch size like 16*16?

### ISSUE THREAD

**Issue by range997996** [keyu-tian/SparK#11]
Hi, thanks for your nice work! It seems it only supports mask patch size of 32x32,if i want to try other size like 16x16/8x8,how should i change the code?

**Comment by keyu-tian** [comment]
Thanks! Before answering your question, I'd clarify one important thing: in SparK, the mask patch size **equals to** the downsample ratio of the CNN.

Here is the reason: when we do mask, we:

1. first generate the mask for the smallest resolution feature map, i.e., generate the `_cur_active` or `active_b1ff` in [line86-87](https://github.com/keyu-tian/SparK/blob/main/spark.py#L86), which is shaped as `[B, 1, fmap_size, fmap_size]`, and would be use to mask the smallest feature map.
3. then progressively upsample it (i.e., expand its 2nd and 3rd dimensions by calling `repeat_interleave(..., 2)` and `repeat_interleave(..., 3)` in [line16](https://github.com/keyu-tian/SparK/blob/main/encoder.py#L16)), for masking those feature maps with larger resolutions.

So if you want a pathc size of 16 or 8, you should implement a CNN model with a downsample ratio of 16 or 8. **Note that** the CNN should implement its `forward` function with an arg named `hierarchy`. You may refer to https://github.com/keyu-tian/SparK/blob/main/models/convnext.py#L78 to see what does `hierarchy` mean and how you should treat it.

After this, I think you can simply run main.sh with `--hierarchy=3` and check if it works. Besides, according to SimMIM, I would suggest to use a larger mask ratio, like 0.75. So you may also use `--mask=0.75`.

If you have any further question u can comment here again.

**Comment by range997996** [comment]
Thanks a lot! It will do me a great favor.

**Comment by keyu-tian** [comment]
@range997996 Hi, we've refactored the code, and for now we believe it can be very convenient for customizing CNN models. You can kindly read https://github.com/keyu-tian/SparK/tree/main/pretrain#tutorial-for-customizing-your-own-cnn-model for the tutorial, hope you enjoy it!

**Comment by junwuzhang19** [comment]
![image](https://github.com/keyu-tian/SparK/assets/116895437/7ee07acf-c150-4e6e-9a8d-846290712d00)
Hi, thanks for your work. I am confused how S4 mask pattern transforms to S2 pattern in this figure, if masking on 32x32 with iteratively upsampling. Is it a mistake ( or I may not fully understand)?

**Comment by keyu-tian** [comment]
@junwuzhang19 Yes you are right. I slightly abuse the correctness in this figure just for better visualization. If the patch size 32 is used, white holes in S1 should strictly be 4x4, rather than 2x2 in the figure.
