### ISSUE TITLE
请问下ppt中的动图是怎么画的

### ISSUE THREAD

**Issue by whuhit** [keyu-tian/SparK#13]
十分感谢TechBeat上的视频分享，文章思路非常清晰，PPT也很漂亮，想请教下，ppt中的网络结构动图是通过什么画的呀

**Comment by keyu-tian** [comment]
(cn version) 谢谢！基本上先是画的静态页面，然后用“平滑”这个切换效果，让PPT自动在不同静态页面之间补帧，得到的动画效果。我们把 slides 文件上传到 https://github.com/keyu-tian/SparK/releases/tag/file_sharing 了，可供下载和查看。

(en version) Thanks! Basically, we're using a lot of "Morph" transitions between slides to animate slides/video. We first make a static slide, duplicate it, and then move some object on the second slide to different places, or add some new objects. Using "Morph" transition between the two slides can automatically animate and move those changed or added object, in a pretty smooth way. Check https://github.com/keyu-tian/SparK/releases/tag/file_sharing for download and viewing.

**Comment by whuhit** [comment]
好的，感谢。
