### ISSUE TITLE
Lr layer decay

### ISSUE THREAD

**Issue by Vickeyhw** [keyu-tian/SparK#15]
Thanks for your excellent work!  I noticed that LR layer decay is not used in ImageNet fine-tuning, but it is used in detection. Why not use layer decay like in transformer fine-tuning?  What influence will it have if layer decay is adopted in ImageNet fine-tuning?

**Comment by keyu-tian** [comment]
Thanks! The lr layer decay is also used in our ImageNet fine-tuning, you could check [downstream_imagenet/arg.py line13-23](https://github.com/keyu-tian/SparK/blob/main/downstream_imagenet/arg.py#L13) to see these values (0.8 or 0.7)

**Comment by Vickeyhw** [comment]
Thanks!
