### ISSUE TITLE
Weights of Resnet with decoder

### ISSUE THREAD

**Issue by Vickeyhw** [keyu-tian/SparK#18]
Thanks for your great work!  Could you please provide the integrated pre-trained weights of Resnet with its decoder?

**Comment by keyu-tian** [comment]
@Vickeyhw Thanks! We'll upload them. You can check the README tomorrow.

**Comment by Vickeyhw** [comment]
Thanks a lot! I just checked the README, but can't find the update.

**Comment by keyu-tian** [comment]
Sorry for being late, you could kindly check them now.
