### ISSUE TITLE
torch.distributed.elastic.multiprocessing.api.SignalException

### ISSUE THREAD

**Issue by shuuchen** [keyu-tian/SparK#19]
Hi,

Thanks for your great work!

I trained with your code but always got the above exception after training for 1 or 2 hours.
I searched and found that was because the terminal window was closed even the model was training in the background with nohup.

Have you also met the same problem? and I just wonder how did you train the models in the background?

Thank you!

**Comment by keyu-tian** [comment]
Thanks!

Sorry but i got no idea about this issue. We use tmux (similar to nohup) to train the models in the background. Maybe you could try it too.

**Comment by shuuchen** [comment]
Thank you. I tried tmux and it worked!
