### ISSUE TITLE
When will the full code be released? 

### ISSUE THREAD

**Issue by zhangzjn** [keyu-tian/SparK#2]
Great work, but when will the full code be released? Thanks

**Comment by keyu-tian** [comment]
Thanks! The full codes including downstream finetuning and visualization are expected to be released by next week.

**Comment by annawoodard** [comment]
Great work-- very exciting paper; thanks for posting the pretraining code. I'm looking forward to the fine-tuning and viz code

**Comment by songkq** [comment]
@keyu-tian Hi, could you please release the visualization code?

**Comment by keyu-tian** [comment]
@songkq @annawoodard @zhangzjn sorry kept you waiting so long, now our fine-tuning code & viz demo (Colab) is ready! We're also working on:

- upload the vis demo to `huggingface`
- upload pretrained weights into `huggingface` and `timm`

Once they finish we would comment here again and paste some notes, thanks!
