### ISSUE TITLE
Can you provide more model pth with decoder?

### ISSUE THREAD

**Issue by WwwwYz666** [keyu-tian/SparK#29]
What an outstanding and admirable work! Due to performance limitations, this experiment cannot be trained on a PC. But I want to try to see the effect of image restoration using different models. I would like to ask if you can provide more pretrain model pth files including decoder.

Just like the pth model in https://github.com/keyu-tian/SparK/blob/main/pretrain/viz_reconstruction.ipynb step 3 .

**Comment by keyu-tian** [comment]
Thank you! For other pths you can find them in `Pretrained weights (with SparK's UNet-style decoder; can be used to reconstruct images)` paragraph in https://github.com/keyu-tian/SparK. We also updated the https://github.com/keyu-tian/SparK/blob/main/pretrain/viz_reconstruction.ipynb, so you can different models like ResNet50 for reconstruction.

**Comment by WwwwYz666** [comment]
I sincerely appreciate your help!
