### ISSUE TITLE
What should i do when input shape is a rectangle ?

### ISSUE THREAD

**Issue by syjabc** [keyu-tian/SparK#32]
Thank you for your excellent work. I want to do some work on audio classification task, and I found it is impossible to keep input shape as a square. What should i do when input tensor is a rectangle，like (128, 600).

**Comment by keyu-tian** [comment]
Well though the current code are not suitable for rectangle input, i think you only need to change a few things to make it work. 

First you can refer to [/pretrain/README.md](https://github.com/keyu-tian/SparK/blob/main/pretrain/README.md) for customizing your audio dataset (and according data preprocessing code) and CNN model.

Then you should make `fmap_size` in [this file](https://github.com/keyu-tian/SparK/blob/main/pretrain/spark.py#L28) a tuple as the shape of rectangle, and change everything related to it.

Then i think things wil work.

**Comment by syjabc** [comment]
Thanks for your thorough and patient responses.
