### ISSUE TITLE
how to finetune resnet in my own dataset?

### ISSUE THREAD

**Issue by merlinxu-zz** [keyu-tian/SparK#35]
hi~I find I can pre-train resnet in my own dataset by replacing the function [build_dataset_to_pretrain] and running /pretrain/main.py ; also I can finetune resnet in Imagenet by running /downstream-imagenet/main.py; but how can I finetune resnet in my own dataset?  when I try to run /pretrain/main.py with args --resume_from=/mypath-to-res50_withdecoder_1kpretrained_spark_style.pth, I will get a error like
File "/workspace/user_code/SparK/pretrain/utils/misc.py", line 180, in load_checkpoint
    missing, unexpected = model_without_ddp.load_state_dict(checkpoint['module'], strict=False)
KeyError: 'module'

**Comment by keyu-tian** [comment]
1. finetune resnet in my own dataset: you can do the similar thing, replace the dataset to yours for finetuning.

2. `--resume_from` is designed for loading and continuing an unfinished pretraining process, so you may not use our finished checkpoint `res50_withdecoder_1kpretrained_spark_style.pth`

**Comment by merlinxu-zz** [comment]
谢谢！许曼玲已收到您的邮件！

**Comment by merlinxu-zz** [comment]
thank you so much!! I have another question: when I run /downstream-imagenet/main.py with my own dataset, I find it calculates accuracy by judging whether the classification predicted by the model is consistent with the classification of the target，but what if my dataset is not Imagenet and I don't have their categery labels? should I treat a picture as a category?（By the way, since the codes use the category label, can it call supervised learning?

**Comment by keyu-tian** [comment]
@merlinxu-zz can you explain your task and dataset to me with more details?

**Comment by merlinxu-zz** [comment]
sure! my dataset is 40w pictures from game scene，but only 2w picture have labels to do object detection task; so I want to use the rest of 38w pictures to do some supervised learning task in the resnet50 network because I use resnet50 as a basebone in my object detection task; should I try to pretrain resnet50 in Spark instead of fituning resnet50 since I thought the fitune code seems to require category labels?

**Comment by keyu-tian** [comment]
ok i see, so you want to continue a self-supervised finetuning on your own dataset (38w images).

First i need to explain that our downstream_finetune codebase is for supervised finetuning. If you want a self-supervised finetuning based on our pretrained checkpoint, see the last line of https://github.com/keyu-tian/SparK/tree/main/pretrain#tutorial-for-pretraining-your-own-dataset, use the `--init_weight` to specify the checkpoint.

As for the dataset, you need to define a new Python class for your dataset, to replace our ImageNetDataset. So "put one picture in one folder to make my dataset the same structure as ImageNet" is not required. Just define your own class.

**Comment by merlinxu-zz** [comment]
thank you for your kindly answer!! it works now!
