### ISSUE TITLE
How to install Tap?

### ISSUE THREAD

**Issue by LinB203** [keyu-tian/SparK#39]
I installed Tap via `pip3 install tap`, but some trouble happen.

```
from tap import Tap
ImportError: cannot import name 'Tap' from 'tap' 
```

**Comment by LinB203** [comment]
sorry, I miss the install.md and I solve it by `pip install typed-argument-parser`.

**Comment by LeeHaoRanRan** [comment]
I would like to ask, how did you solve the tap installation problem
