### ISSUE TITLE
How do I know it is pretraining works instead of longer finetuning epochs?

### ISSUE THREAD

**Issue by rayleizhu** [keyu-tian/SparK#40]
I notice that you set the finetuning epochs as 200 or 400.

https://github.com/keyu-tian/SparK/blob/a64bdf729f9491b75d94163982750911e1f91234/downstream_imagenet/arg.py#L16

 However,

* the standard supervised training only runs for 300 epochs (w/o 1600 or 800 pretraining epochs).
* in MIM works (e.g. MAE and ConvNextV2), they typically finetune 100 epochs.

Did you try 100 epoch schedule? Can you also kindly share the result under such a setting?

**Comment by keyu-tian** [comment]
We basically follow A2-MIM's 300-epoch finetuning setting (i.e., the Resnet Strikes Back/RSB A2), and set 200/400 ep for smaller/larger models respectively. We exclude the 100-epoch RSB A3 setting since it uses a different resolution (160), but if it is of interest we would have a try.

btw, the convnextv2 uses 400 or 600 for their smaller models.

**Comment by rayleizhu** [comment]
Thanks for your quick response.

>  We exclude the 100-epoch RSB A3 setting since it uses a different resolution (160), but if it is of interests we would have a try.

I think the 100 ep setting is important, otherwise, it is difficult for follow-up works to compare with existing works (Spark, ConvNextV2, etc.) in a fair way because of inconsistent evaluation protocols. 

Besides, I think it is more reasonable to finetune pre-trained models with no more than 300 epochs, which is used in the supervised baseline. Otherwise, it is hard to say whether the performance gain comes from longer finetuning or better initialization provided by MIM.

**Comment by rayleizhu** [comment]
> I see. But I would suggest not focusing too much on ImageNet finetuning. I feel the best way to justify whether MIM makes sense is to evaluate it on REAL downstream tasks (i.e., not on ImageNet), because doing pretraining and finetuning on the same dataset can be kind of like a "data leakage", and dosen't match our eventual goals of self-supervised learning.

This makes sense to me. Thanks for the explanation.
