### ISSUE TITLE
About reproducing MAE with ViT-S

### ISSUE THREAD

**Issue by LinB203** [keyu-tian/SparK#41]
I notice that you reproduce the result of MAE with ViT-S by using official codes, but there is no decoder design in the official codes. 
I wonder that how many layers you use in decoder of ViT-S, also decoder_dim and num_head?

**Comment by keyu-tian** [comment]
We're using patch_size=16, embed_dim=384, depth=12, num_heads=6, decoder_embed_dim=256, decoder_depth=8, decoder_num_heads=8, mlp_ratio=4.

**Comment by LinB203** [comment]
clearly, thx.

**Comment by LinB203** [comment]
What's about the pre-train script and fine-tune script?
and I guess that the result of ViT-S is produced by the original code, just changed training scripts. Am I right?
Can I use your scripts to reproduce the result of ViT-S?

**Comment by keyu-tian** [comment]
@LinB203 Yes you should use mae's official code.

**Comment by keyu-tian** [comment]
Yes, we just modify the architecture.
