### ISSUE TITLE
How do you adjust lr and wd?

### ISSUE THREAD

**Issue by pengcheng93** [keyu-tian/SparK#43]
Hi,

Thanks so much for your great work!
I am confused about how you adjust the lr and weight_decay. In pretrain/utils/lr_control.py/lr_wd_annealing, I think lr and wd are only acquired and not changed.

Thank you!

**Comment by keyu-tian** [comment]
in that function we modify the lr and weight_decay in`optimizer.param_groups`, so it will acquire and change lr/wd in the same time.
