### ISSUE TITLE
Contrastive learning methods performance in paper

### ISSUE THREAD

**Issue by Vickeyhw** [keyu-tian/SparK#47]
Thanks for your great work! Does these contrastive learning methods' performance on ImageNet refer to finetuning results? If so, since those papers only report linear evaluation results, where did you get the finetuning score?

**Comment by keyu-tian** [comment]
Yes we use the codebase of ["ResNet Strikes Back"](https://arxiv.org/abs/2110.00476) to finetune CL pretrained weights. We use the RSB A2 configuration.
