### ISSUE TITLE
稀疏卷积问题

### ISSUE THREAD

**Issue by MENG1996** [keyu-tian/SparK#49]
您好，看代码后发现sp_conv_forward的 returning_active_ex=True，也就是说在卷积部分没有进行稀疏计算，而是在batchnorm和layernorm上进行稀疏计算吗？
感谢您的工作！

**Comment by keyu-tian** [comment]
是的，也可以说都没有使用真的稀疏卷积，都是使用的pytorch操作模拟稀疏卷积的定义，计算结果和稀疏卷积一致，但是计算过程没有真正的稀疏性（无法通过稀疏性省显存）
