### ISSUE TITLE
Finetuning epochs

### ISSUE THREAD

**Issue by ds2268** [keyu-tian/SparK#52]
Dear authors,

with regards to U2 from the reviewer 71p6: "The sparse convolution seems cannot largely speed up the training process like MAE for ViT and the model requires 300 epoch fine-tuning that is the same as the configuration of training from scratch."

I think that the reviewer had in mind that for MAE, the authors only fine-tuned for 100 (ViT-B) and 50 (ViT-L/H) epochs (MAE paper, A.1, Table 9). The supervised models that were trained from scratch in the MAE paper were trained for 300 epochs (MAE paper, A.2, Table 11).

SparK was fine-tuned for 300 epochs, which is the same configuration as training supervised ViTs from scratch. MAE thus achieved comparable performance with 3-6x less fine-tuning epochs.

Can you report your results also with the same fine-tuning configuration (50/100 epochs) as used in MAE? Only then the comparison can be fair.

Comment from: https://openreview.net/forum?id=NRxydtWup1S

**Comment by ds2268** [comment]
Partially answered in #40.

**Comment by keyu-tian** [comment]
Yes in #40 we explained some. We didn't tune much on finetuning like convnextv2, and just copied the recipes from AAMIM or RSB. Fewer epochs (with hyperparameter searching) are worty to try, but we currently have no computational resources. Maybe one can use our checkpoint and codebase to do that.
