### ISSUE TITLE
Spark.forward

### ISSUE THREAD

**Issue by ricklisz** [keyu-tian/SparK#61]
Dear author, 

I wonder what is the use of SparK.forward in line 156 in main.py from pretrain? Is that necessary to call the forward function? I believe the defined model is actually model_without_ddp. 

Similar issue in pretrain/viz_reconstruction, where the function show calls another spark.forward. 

Looking forward to your response!

**Comment by keyu-tian** [comment]
@ricklisz those forward are useless and can be removed. I wrote them just for more hints of my IDE.
