### ISSUE TITLE
Are there any plans to make a port to tensorflow and Keras?

### ISSUE THREAD

**Issue by noahcjones** [keyu-tian/SparK#68]
Hi,
My existing codebase is using Tensorflow/Keras and I want to know if the authors knew of or planned to release an official version for pretraining and finetuning that works with Keras?

**Comment by keyu-tian** [comment]
Hi @noahcjones, we have less mastery of other frameworks and it would be very welcome if you could migrate our pytorch implementation to them ❤. We can involve in code reviews if you want.
