### ISSUE TITLE
ConvNext B for reconstruct images

### ISSUE THREAD

**Issue by M-SunRise** [keyu-tian/SparK#75]
Can you provide the weights of ConvNext-B for me?

**Comment by keyu-tian** [comment]
Hi @M-SunRise, you can click and expand the "Pretrained weights (with SparK's UNet-style decoder; can be used to reconstruct images)" in [README](https://github.com/keyu-tian/SparK) for downloading them.

**Comment by M-SunRise** [comment]
I only find ConvNext-S and L, not find B.

**Comment by keyu-tian** [comment]
@M-SunRise oh I remember now. I didn't save the convnext-B's checkpoint with decoder. So currently only S and L are available for reconstruction.
