### ISSUE TITLE
A Code Issue About “pretrain/main.py” 

### ISSUE THREAD

**Issue by lynnz7** [keyu-tian/SparK#79]
Hello, your work is very meaningful and effective. While reviewing your code, I noticed a SparK.forward statement on line 156 in SparK/pretrain/main.py. I'm not quite familiar with this usage. Is it a typo or does it serve another purpose? I hope you can clarify this. Thank you.

**Comment by keyu-tian** [comment]
Thank you @lynnz7. It's a useless statement and can be removed. I did this only for more hints from PyCharm.

**Comment by lynnz7** [comment]
Thank you for your thoughtful response, and wishing you a Happy Chinese New Year!
