### ISSUE TITLE
The plan to release the visualization code of image reconstruction and “mask pattern vanishing” issue

### ISSUE THREAD

**Issue by songkq** [keyu-tian/SparK#9]
@keyu-tian Hi, could you please share the visualization code? Thanks.

**Comment by keyu-tian** [comment]
Would be ready in this week, thanks for your waiting!

**Comment by songkq** [comment]
Thanks for your contribution.

**Comment by Mark-Laohu** [comment]
> Would be ready in this week, thanks for your waiting!

Thanks for your share!!!

**Comment by keyu-tian** [comment]
Hi @songkq @Mark-Laohu, the viz code for [mask-and-reconstruct](https://github.com/keyu-tian/SparK/blob/main/pretrain/viz_reconstruction.ipynb) and [mask pattern vanishing](https://github.com/keyu-tian/SparK/blob/main/pretrain/viz_spconv.ipynb) is ready. Hope it helps. Leave any questions here. Thanks!

**Comment by songkq** [comment]
@keyu-tian Thanks!
